
import { useEffect, useRef } from "react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { ArrowRight, Zap } from "lucide-react";
import heroWebDev from "@/assets/hero-web-dev.jpg";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

export function HeroSection() {
  const scrollToProjects = () => {
      document.getElementById("projects")?.scrollIntoView({ behavior: "smooth" });
        };
          const scrollToContact = () => {
              document.getElementById("contact")?.scrollIntoView({ behavior: "smooth" });
                };

                  const letters = "Innovation".split("");

                    // Ref for GSAP animation
                      const buildingRef = useRef(null);

                        useEffect(() => {
                            if (buildingRef.current) {
                                  gsap.from(buildingRef.current, {
                                          scrollTrigger: {
                                                    trigger: buildingRef.current,
                                                              start: "top 85%",
                                                                        end: "top 50%",
                                                                                  toggleActions: "play none none reset",
                                                                                          },
                                                                                                  y: -150,
                                                                                                          opacity: 0,
                                                                                                                  ease: "bounce.out",
                                                                                                                          duration: 1.5,
                                                                                                                                });
                                                                                                                                    }
                                                                                                                                      }, []);

                                                                                                                                        return (
                                                                                                                                            <section id="home" className="min-h-screen flex items-center relative overflow-hidden">
                                                                                                                                                  {/* Background */}
                                                                                                                                                        <div className="absolute inset-0">
                                                                                                                                                                <img src={heroWebDev} alt="Professional Web Development" className="w-full h-full object-cover" />
                                                                                                                                                                        <div className="absolute inset-0 bg-gradient-to-r from-black/100 via-black/50 to-transparent" />
                                                                                                                                                                              </div>

                                                                                                                                                                                    {/* Content */}
                                                                                                                                                                                          <div className="relative z-10 w-full h-full flex items-center">
                                                                                                                                                                                                  <div className="w-full lg:w-1/2 space-y-8 text-white p-8 lg:p-12">
                                                                                                                                                                                                            <motion.div
                                                                                                                                                                                                                        initial={{ opacity: 0, x: -50 }}
                                                                                                                                                                                                                                    animate={{ opacity: 1, x: 0 }}
                                                                                                                                                                                                                                                transition={{ duration: 0.8 }}
                                                                                                                                                                                                                                                            className="space-y-6"
                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                  <div className="flex items-center space-x-2 text-primary">
                                                                                                                                                                                                                                                                                                <Zap className="h-5 w-5" />
                                                                                                                                                                                                                                                                                                              <span className="text-sm font-semibold tracking-wide uppercase">Premium Web Development</span>
                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                      {/* Heading */}
                                                                                                                                                                                                                                                                                                                                                  <h1 className="text-4xl md:text-6xl font-bold leading-tight">
                                                                                                                                                                                                                                                                                                                                                                <span ref={buildingRef} className="block">Building Digital</span>
                                                                                                                                                                                                                                                                                                                                                                              <span className="block text-primary">Excellence</span>
                                                                                                                                                                                                                                                                                                                                                                                            <span className="block">
                                                                                                                                                                                                                                                                                                                                                                                                            with{" "}
                                                                                                                                                                                                                                                                                                                                                                                                                            {letters.map((letter, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                              <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={i}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="bounce-letter"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{ animationDelay: `${i * 0.12}s` }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {letter}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xl text-white/90 leading-relaxed max-w-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Crafting cutting-edge web solutions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </motion.div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Buttons */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <motion.div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            initial={{ opacity: 0, x: -50 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        animate={{ opacity: 1, x: 0 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transition={{ duration: 0.8, delay: 0.2 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="flex flex-col sm:flex-row gap-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={scrollToProjects}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  size="lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="bg-primary hover:bg-primary-glow text-primary-foreground px-8 py-6 text-lg font-semibold rounded-xl hover:scale-105 transition-all duration-300 shadow-lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Explore Our Work
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <ArrowRight className="ml-2 h-5 w-5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={scrollToContact}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            variant="outline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          size="lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="border-2 border-white text-white hover:bg-white hover:text-[#333333] px-8 py-6 text-lg font-semibold rounded-xl hover:scale-105 transition-all duration-300 bg-transparent"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Get in Touch
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Ripple bounce effect for Innovation */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <style>{`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          @keyframes rippleBounce {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0%, 100% {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                transform: translateY(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: rgba(255, 255, 255, 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                50% {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            transform: translateY(-16px);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: hsl(var(--primary));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .bounce-letter {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            display: inline-block;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      will-change: transform, color;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                animation: rippleBounce 0.9s ease-in-out infinite;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              `}</style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    